export enum LoggerName {
  CLASS = 'CLASS',
  FUNCTION = 'FUNCTION',
  REQUEST = 'REQUEST'
}

export enum MCSState {
  VERSION_TAG_AND_SIZE,
  TAG_AND_SIZE,
  SIZE,
  BYTES
}

export enum MCSTag {
  HEARTBEAT_PING,
  HEARTBEAT_ACK,
  LOGIN_REQUEST,
  LOGIN_RESPONSE,
  CLOSE,
  //   MESSAGE_STANZA,
  //   PRESENCE_STANZA,
  IQ_STANZA = 7,
  DATA_MESSAGE_STANZA
  //   BATCH_PRESENCE_STANZA,
  //   STREAM_ERROR_STANZA,
  //   HTTP_REQUEST,
  //   HTTP_RESPONSE,
  //   BIND_ACCOUNT_REQUEST,
  //   BIND_ACCOUNT_RESPONSE,
  //   TALK_METADATA,
  //   NUM_PROTO_TYPES
}
