name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: pnpm install
      - name: Test Coverage
        run: pnpm vitest run --coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          VITE_ACG_ID: ${{ secrets.VITE_ACG_ID }}
          VITE_ACG_SECURITY_TOKEN: ${{ secrets.VITE_ACG_SECURITY_TOKEN }}
          VITE_ACG_TOKEN: ${{ secrets.VITE_ACG_TOKEN }}
          VITE_FCM_SENDER_ID: ${{ secrets.VITE_FCM_SENDER_ID }}
          VITE_FCM_SERVER_KEY: ${{ secrets.VITE_FCM_SERVER_KEY }}
          VITE_FCM_TOKEN: ${{ secrets.VITE_FCM_TOKEN }}
          VITE_FCM_TOKEN_2: ${{ secrets.VITE_FCM_TOKEN_2 }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_GOOGLE_SERVICE_ACCOUNT: ${{ secrets.VITE_GOOGLE_SERVICE_ACCOUNT }}
          VITE_VAPID_KEY: ${{ secrets.VITE_VAPID_KEY }}
